name: "🚀 Feature Request"
description: "Propose a new feature or enhancement for the client."
labels: ["feature", "enhancement"]
title: "Feature: "
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain what this feature should do and why it’s needed.
      placeholder: "Currently, it's not possible to submit answers through the client. This feature should introduce..."

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define the conditions that must be met for this feature to be considered complete.
      placeholder: |
        Example:
        - [ ] New API endpoint implemented
        - [ ] Client exposes a public method
        - [ ] Tests and documentation updated


  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Add any implementation hints, related issues, or API references.
      placeholder: "Consider adding helper methods to simplify event payloads..."
